{% set name = "ocetrac" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: ocetrac-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db1e5d13839db783f00fe5eb3c714379e6e43d8fe2911d9be9bcd4cf6364f298

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - xarray
    - dask
    - scipy
    - scikit-image

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - ocetrac

about:
  home: https://github.com/ocetrac/ocetrac
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Label and track unique geospatial features from gridded datasets
  doc_url: https://ocetrac.readthedocs.io/

extra:
  recipe-maintainers:
    - hscannell
